blank_issues_enabled: false
contact_links:
  - name: Ask a Question / General Discussion
    url: https://github.com/Python-Nigeria/pynigeria-backend/discussions
    about: Use GitHub Discussions for questions and general conversation.
