# Generated by Django 5.1.4 on 2026-04-14 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="whatsapp_username",
            new_name="username",
        ),
        migrations.AddField(
            model_name="profile",
            name="full_name",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="title",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
