# Generated by Django 5.1.4 on 2026-04-09 00:01

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("location", models.CharField(max_length=255, null=True)),
                ("description", models.TextField(null=True)),
                ("website", models.URLField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="BookmarkFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("folder_name", models.CharField(max_length=255)),
                ("folder_description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmark_folders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("job_title", models.CharField(max_length=255)),
                ("job_description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Published", "Published"),
                            ("Archived", "Archived"),
                            ("Expired", "Expired"),
                        ],
                        default="Draft",
                        max_length=20,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("Private", "Private"),
                            ("Internal", "Internal"),
                            ("Public", "Public"),
                            ("Featured", "Featured"),
                        ],
                        default="Private",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("application_deadline", models.DateTimeField(null=True)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("Full Time", "Full Time"),
                            ("Part Time", "Part Time"),
                            ("Contract", "Contract"),
                            ("Internship", "Internship"),
                            ("Voluntary", "Voluntary"),
                        ],
                        default="Full Time",
                        max_length=255,
                    ),
                ),
                (
                    "salary",
                    models.DecimalField(decimal_places=2, max_digits=17, null=True),
                ),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("applications_count", models.PositiveIntegerField(default=0)),
                ("version", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("slug", models.UUIDField(db_index=True, unique=True)),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="job_listing_api.company",
                        to_field="name",
                    ),
                ),
                (
                    "original_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revisions",
                        to="job_listing_api.job",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Saved", "Saved"),
                            ("Applied", "Applied"),
                            ("Interviewing", "Interviewing"),
                            ("Rejected", "Rejected"),
                            ("Offered", "Offered"),
                            ("Archived", "Archived"),
                        ],
                        default="Saved",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookmarks",
                        to="job_listing_api.bookmarkfolder",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="job_listing_api.job",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "skill_level",
                    models.CharField(
                        choices=[
                            ("Beginner", "Beginner"),
                            ("Intermidiate", "Intermidiate"),
                            ("Advanced", "Advanced"),
                        ],
                        default="Beginner",
                        max_length=255,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_skills",
                        to="job_listing_api.job",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="job_listing_api.skill",
                        to_field="name",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="job",
            name="skills",
            field=models.ManyToManyField(
                db_index=True,
                related_name="jobs",
                through="job_listing_api.JobSkill",
                to="job_listing_api.skill",
            ),
        ),
        migrations.AddIndex(
            model_name="bookmarkfolder",
            index=models.Index(
                fields=["folder_name"], name="job_listing_folder__bf18d4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bookmarkfolder",
            unique_together={("user", "folder_name")},
        ),
        migrations.AddIndex(
            model_name="bookmark",
            index=models.Index(
                fields=["user", "status"], name="job_listing_user_id_b114f2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookmark",
            index=models.Index(
                fields=["created_at"], name="job_listing_created_df8165_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bookmark",
            unique_together={("user", "job")},
        ),
        migrations.AlterUniqueTogether(
            name="jobskill",
            unique_together={("job", "skill")},
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["original_job", "version"],
                name="job_listing_origina_baf409_idx",
            ),
        ),
    ]
