# Generated by Django 5.1.4 on 2026-04-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_listing_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="slug",
            field=models.UUIDField(blank=True, db_index=True, unique=True),
        ),
    ]
