# Generated by Django 5.1.4 on 2026-03-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_otp_email_sent",
        ),
        migrations.AddField(
            model_name="user",
            name="auth_provider",
            field=models.CharField(db_index=True, default="password", max_length=50),
        ),
        migrations.AlterField(
            model_name="otpcode",
            name="code",
            field=models.CharField(db_index=True, max_length=6),
        ),
        migrations.AlterField(
            model_name="otpcode",
            name="expiry",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
